Pizzeria/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pizzas.urls')),
]

pizzas/urls.py
from django.urls import path

from . import views 

app_name = 'pizzas'

urlpatterns = [
    path('',views.index,name='index'),
    path('menu',views.menu,name='menu'),
    path('menu/<int:item_id>/',views.item,name='item'),

    ]

pizzas/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Pizza(models.Model):
    pizza_name = models.CharField(max_length=200)

    def __str__(self):
        return self.pizza_name

class Topping(models.Model): 
    item = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    topping_name = models.TextField(max_length=100)

    def __str__(self):
        return self.topping_name

class Photo(models.Model):
    photo = models.ForeignKey(Pizza, on_delete=models.CASCADE)
    photo_file = models.ImageField(null=True)

    #def __str__(self):
    #    return self.photo_file

pizzas/views.py
from django.shortcuts import render, redirect
from .models import *

# Create your views here.
def index(request): 
    return render(request, 'pizzas/index.html')

def menu(request):
    menu = Pizza.objects.all()

    context = {'all_menu':menu}
    
    return render(request, 'pizzas/menu.html', context)

def item(request, item_id):
    p = Pizza.objects.get(id=item_id)
    
    entries = Topping.objects.filter(item=p)

    context = {'item':p, 'entries':entries}
    
    return render(request, 'pizzas/item.html', context)

pizzas/templates/pizzas/base.html
<p>
    <a href="{% url 'pizzas:index' %}">Pizzeria</a>
    <a href="{% url 'pizzas:menu' %}">Menu</a>
</p>

{% block content %}


{% endblock content %}

pizzas/templates/pizzas/index.html
{% extends "pizzas/base.html" %}

{% block content %}

<p style="color:darkgreen;font-size:28px;"> Pizzeria </p>

<p style="color:red;font-size:38px;"> Welcome to the Pizzeria! Browse our menu now.</p>

<img src="https://www.thespruceeats.com/thmb/MD-dSsFP6k5XBSk9XcdOIfnF4K0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/prosciutto-pizza-4844358-hero-04-c0a6f73057ce4fed88982b75a5c2c8e1.jpg" height="600px" width="700px">

{% endblock content %}

pizzas/templates/pizzas/item.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Pizza: {{ item }} </p>
<img src="https://www.jessicagavin.com/wp-content/uploads/2022/02/meat-lovers-pizza-28-1200.jpg" height="500px" width="500px">

<ul>
    <p>Toppings</p>
    {% for e in entries %}

    <li> {{ e.topping_name }} </li>

    {% empty %}
    <li> No entries for this item have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}

pizzas/templates/pizzas/menu.html
{% extends "pizzas/base.html" %}

{% block content %}

<p> Menu </p>

<ul>
    {% for item in all_menu %}

    <li> 
        <a href="{% url 'pizzas:item' item.id %}"> {{ item }} </a>
    </li>

    {% empty %}
    <li> No pizzas have been added yet.</li>
    {% endfor %}
</ul>

{% endblock content %}